### ISSUE TITLE
examples for streaming data 

### ISSUE THREAD

**Issue by rbabaee2014** [thinger-io/Linux-Client#1]
Hi!
is there any examples for streaming data from a raspberry pi? I found examples on arduino in the website, but didn't find anything for raspberry pi... 
I need to stream a temperature sensors results .

**Comment by abhinuvpitale** [comment]
+1 to this, are there going to be updates in the src code for the linux part of it?

**Comment by alvarolb** [comment]
Hi, in fact, the main Arduino Core files, like thinger.h, which contains those functions, can be moved easily to the Linux Client Core. We will update it soon in an official release, as we will provide other functions.

**Comment by abhinuvpitale** [comment]
Is there an estimate date on the Linux Client Core release? Can you update the code in a testing branch in the Linux Core? I could help you build it. @alvarolb

**Comment by bautisflow** [comment]
Hello @rbabaee2014 @abhinuvpitale ,

As of today the issue has been resolved by updating the core files.
I'll leave here an example on which I stream the uptime of the machine onto the Thinger.io platform:

```
#include "thinger/thinger.h"

#define USER_ID             "******"
#define DEVICE_ID           "******"
#define DEVICE_CREDENTIAL   "******"

#include <sys/sysinfo.h>

int main(int argc, char *argv[])
{
    thinger_device thing(USER_ID, DEVICE_ID, DEVICE_CREDENTIAL);

    // define thing resources here. i.e, this is a sum example
    thing["sum"] = [](pson& in, pson& out){
        out["result"] = (int) in["value1"] + (int) in["value2"];
    };

    thing ["uptime"] >> [](pson& out) {
        /* Obtain system statistics. */
        struct sysinfo si;
        sysinfo (&si);

        out = si.uptime;
    };

    while(true) {
        thing.handle(); // handle will replace start at the bottom

        // stream all desired resources
        thing.stream(thing["uptime"]); 
    }

//    thing.start();
    return 0;
}
```

Note that for streaming, instead of using `thing.start()` at the bottom of the program, an infinite loop needs to be declared with `thing.handle()` as well as any of the streaming resources.

We hope you find it useful. Let us know if we can help with anything else.

Kind Regards.
